name: easy_park_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  stylish_bottom_bar: 
  cached_network_image: ^3.3.0
  fl_country_code_picker: ^0.1.9+1
  flutter_otp_text_field: ^1.1.1
  otp_timer_button: ^1.1.0
  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.1.1
  geocoding: ^2.0.4
  flutter_osm_plugin: ^0.70.3
  geolocator: ^10.1.0
  flutter_timer_countdown: ^1.0.7
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.65.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_timezone: ^1.0.8
  http: ^1.1.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  image_picker: ^1.0.5
  flutter_slidable: ^3.0.1
  socket_io_client: ^2.0.3+1
  bubble: ^1.2.1
  timeago: ^3.6.0
  pin_code_fields: ^8.0.1
  smooth_page_indicator: ^1.1.0
  grouped_list: ^5.1.2
  readmore: ^2.2.0
  flutter_svg_provider: ^1.0.7
  qr_flutter: ^4.1.0
  phonepe_payment_sdk: ^2.0.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/deatils.png

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/font/NunitoSans-Regular.ttf
        - asset: assets/font/NunitoSans-Medium.ttf
          weight: 500
        - asset: assets/font/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/NunitoSans-Bold.ttf
          weight: 700
        - asset: assets/font/NunitoSans-ExtraBold.ttf
          weight: 800
